### ISSUE TITLE
Upgrade Tekton to 0.32.2

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/community#344]
This upgrade will enable many new features which are captured/tracked in the parent issue as features. As well as bring us to the release from March 2022 which is relatively recent and would stop us just prior to the deprecation of Kubernetes 1.20 from support

**Upgrade Summary**
- 0.27.3 
  - compatibility with Kubernetes 1.22
- 0.28.x
  - Terminating pods so resource quotas are now able to be used properly.
  - `.` notation back in scope for parameters. e.g $(params["foo.bar"])
  - [Cached Entrypoint](https://github.com/tektoncd/pipeline/pull/4188) this will fix a workaround that was put in place internally in IBM to handle the load in pulling images from rate-limited repos [@morarucostel @gchickma]
  - Label changes
- 0.29: 
  - further updates to dot notation based parameters and onError promoted to beta.
- 0.30.0
  -  Kubernetes 1.20 is the new minimum required version 
- 0.31.0
  - Fixes
- 0.32.2
  - Security Fixes

**Comment by tlawrie** [comment]
The current CDF helm chart does not support past 0.29 of Tekton.

There is a PR in progress that would support a helm chart for the operator -> https://github.com/tektoncd/operator/pull/627 but its not ready yet.

I have, for now, used the release YAML rather than the helm chart.

**Decision**
1. Leave the helm chart as a child chart and replace when the above PR is complete
2. Remove the helm chart as a child chart and make as a dependency in the Install instructions to install Tekton separately.

**Comment by tlawrie** [comment]
Also. currently tested on Kube 1.22.6 using AKS and the YAML manifest installation method

**Comment by morarucostel** [comment]
@morarucostel can you please have a look.

**Comment by tlawrie** [comment]
Raised a related GitHub issue to track the Helm chart dependency -> https://github.com/boomerang-io/roadmap/issues/355
