### ISSUE TITLE
Loader - Upgrade to Java 18 and newer versions of dependencies

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/community#367]

**Comment by tlawrie** [comment]
Hi @amhudson @gchickma is there an update on how this is going? ideally it would be good if all the microservices were at Java 18 before we go live with v4 of Flow.

**Comment by amhudson** [comment]
Still haven't found a solution to resolve the issues with migrating the loader to Java 18.

**Comment by tlawrie** [comment]
Hey @amhudson @gchickma is there an update to this task? Loader is the only microservice not on Java 18

**Comment by amhudson** [comment]
No, haven't been able to get back to this. In a lot of directions on my end.

**Comment by tlawrie** [comment]
Updated to Java 17 and Spring Boot 3
