### ISSUE TITLE
Workflow - Upgrade to Java 18

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/community#389]
Upgrade the Workflow service to Java 18

**Comment by tlawrie** [comment]
Potentially blocked by the Lib Scheduling. @amhudson @marcusdroy any thoughts on how we upgrade the java version when we are using lib.scheduling which is a fork of a discontinued Java project?

**Comment by tlawrie** [comment]
Hi @amhudson  any update on this?

**Comment by amhudson** [comment]
@tlawrie I haven't had a moment to further investigate
