### ISSUE TITLE
RFE: New filter on Flow / Activity screen to view tasks with pending "wait for event" tasks

### ISSUE THREAD

**Issue by gchickma** [boomerang-io/community#84]
It would be very handy to see which Flow workflows are waiting on external events, in particular from a support perspective.

**Comment by Okisa** [comment]
Hey @BenjaminRuby @tlawrie ! I don't know if I understood the task correctly, but we currently do have a filter for Waiting state of a workflow execution, but as I could see until now is that Executions that are waiting for events are still being showed as In Progress. There are some tasks on ocp dev where we can see this, like here. Not sure if in this case we should in fact create another filter or ask the service channel to update those states. https://ocp2.cloud.boomerangplatform.net/dev/flow/apps/flow/activity/608fef1a2813fb1b04d52a69/execution/60acf7e4fe05702f64391b56

**Comment by tlawrie** [comment]
Interesting. Great investigation.

@marcusdroy @BenjaminRuby any thoughts here?

**Comment by tlawrie** [comment]
Waiting is added as a status
